// This is a simplified manifest file for SvelteKit
// In a real application, this would be generated by the SvelteKit build process

export const manifest = {
  appDir: '_app',
  appPath: '_app',
  assets: new Set(['favicon.png']),
  mimeTypes: { '.png': 'image/png' },
  _: {
    entry: {
      file: '_app/immutable/start.js',
      imports: ['_app/immutable/entry/start.js'],
      stylesheets: []
    },
    nodes: [
      {
        module: '_app/immutable/entry/layout.js',
        imports: ['_app/immutable/entry/layout.js'],
        stylesheets: []
      },
      {
        module: '_app/immutable/entry/pages/_page.js',
        imports: ['_app/immutable/entry/pages/_page.js'],
        stylesheets: []
      },
      {
        module: '_app/immutable/entry/pages/login/_page.js',
        imports: ['_app/immutable/entry/pages/login/_page.js'],
        stylesheets: []
      }
    ],
    routes: [
      {
        id: '/',
        pattern: /^\/$/,
        names: [],
        types: [],
        page: { layouts: [0], errors: [0], leaf: 1 },
        endpoint: null
      },
      {
        id: '/login',
        pattern: /^\/login\/?$/,
        names: [],
        types: [],
        page: { layouts: [0], errors: [0], leaf: 2 },
        endpoint: null
      },
      {
        id: '/api/users',
        pattern: /^\/api\/users\/?$/,
        names: [],
        types: [],
        page: null,
        endpoint: () => import('../../../routes/api/users/+server.js')
      },
      {
        id: '/api/users/[id]',
        pattern: /^\/api\/users\/([^/]+?)\/?$/,
        names: ['id'],
        types: [null],
        page: null,
        endpoint: () => import('../../../routes/api/users/[id]/+server.js')
      },
      {
        id: '/api/messages',
        pattern: /^\/api\/messages\/?$/,
        names: [],
        types: [],
        page: null,
        endpoint: () => import('../../../routes/api/messages/+server.js')
      },
      {
        id: '/api/operations',
        pattern: /^\/api\/operations\/?$/,
        names: [],
        types: [],
        page: null,
        endpoint: () => import('../../../routes/api/operations/+server.js')
      },
      {
        id: '/api/operations/[id]',
        pattern: /^\/api\/operations\/([^/]+?)\/?$/,
        names: ['id'],
        types: [null],
        page: null,
        endpoint: () => import('../../../routes/api/operations/[id]/+server.js')
      },
      {
        id: '/api/departments',
        pattern: /^\/api\/departments\/?$/,
        names: [],
        types: [],
        page: null,
        endpoint: () => import('../../../routes/api/departments/+server.js')
      }
    ],
    matchers: {}
  }
};
